// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiY47xTM-r_8BPI5MY3yLeyu1IUoZq0Co',
    appId: '1:866093556880:web:289225a14e23623fdb6415',
    messagingSenderId: '866093556880',
    projectId: 'tugas-water-level',
    authDomain: 'tugas-water-level.firebaseapp.com',
    databaseURL: 'https://tugas-water-level-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-water-level.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf4_QUCMEvs7R54HS7DsTFEUhJ8nVQV24',
    appId: '1:866093556880:android:fe6dc9f8bff57e87db6415',
    messagingSenderId: '866093556880',
    projectId: 'tugas-water-level',
    databaseURL: 'https://tugas-water-level-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-water-level.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6vc59nC5FA6XQ-LX74NbX6RH27s4uFVk',
    appId: '1:866093556880:ios:3460e8f2bef1700cdb6415',
    messagingSenderId: '866093556880',
    projectId: 'tugas-water-level',
    databaseURL: 'https://tugas-water-level-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-water-level.appspot.com',
    iosBundleId: 'com.example.finalCimming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6vc59nC5FA6XQ-LX74NbX6RH27s4uFVk',
    appId: '1:866093556880:ios:de84a3538159ef37db6415',
    messagingSenderId: '866093556880',
    projectId: 'tugas-water-level',
    databaseURL: 'https://tugas-water-level-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-water-level.appspot.com',
    iosBundleId: 'com.example.finalCimming.RunnerTests',
  );
}
